### ISSUE TITLE
update ifcModel then write in file

### ISSUE THREAD

**Issue by ManoChanda** [opensourceBIM/IfcPlugins#5] opened 2017-08-18 09:30 UTC
Your previous code works fines for reading and writing an ifc model. But once we modify the ifcModel, it will not write the updated model into a new file, and writes the same previous one before modification.

Guide me to write the modified model into the file

**Comment by rubendel** [comment] 2017-08-18 09:44
This is a duplicate of https://github.com/opensourceBIM/BIMserver/issues/591#issuecomment-323308176

**Closed by rubendel** 2017-08-18 09:44 UTC
