### ISSUE TITLE
working with ifc4

### ISSUE THREAD

**Issue by mhdfahadCS** [opensourceBIM/IfcPlugins#16] opened 2019-03-06 12:30 UTC
Can you please guide me how to work with ifc4, your test works for ifc2x3, now I need to upgrade.

thanks in advance for your help

**Comment by mhdfahadCS** [comment] 2019-03-06 13:24
I am getting this error on my input ifc4 file

org.bimserver.plugins.deserializers.DeserializeException: Error on line 143: Value .SPACE. indicates enum type but EDouble expected

**Comment by rubendel** [comment] 2019-03-07 07:38
Can you share the IFC4 file? By the sounds of it it's probably an invalid file. Also please add more info about which versions of BIMserver and plugins

**Comment by mhdfahadCS** [comment] 2019-03-07 09:26
Dear rubendel, I have sent you in a message, cant put here openly, thanks in advance for your help

**Comment by mhdfahadCS** [comment] 2019-03-07 10:44
I dont find Shared 1.5.126-SNAPSHOT dependancy as mentioned in your POM placed along with this project

**Comment by mhdfahadCS** [comment] 2019-03-07 11:19
It changed POM and it worked with Shared 1.5.125, thanks alot for the source code

**Comment by mhdfahadCS** [comment] 2019-03-07 11:41
I have tested various IFC4 models, I have the following exception on 1 file name=20160125RME_2010_Trapelo_const.ifc";
org.bimserver.plugins.deserializers.DeserializeException: Error on line 1047614:  (The value of type 'org.eclipse.emf.ecore.impl.EClassImpl@5c77053b (name: IfcBuildingElementProxy) (instanceClassName: null) (abstract: false, interface: false)' must be of type 'org.eclipse.emf.ecore.impl.EClassImpl@51684e4a (name: IfcDistributionElement) (instanceClassName: null) (abstract: false, interface: false)') #1837325= IFCRELCONNECTSPORTTOELEMENT('17M7y2Pln5bRI19Gx_xsUv',#42,'672563|17M7y2Pln5bRI19Gx_xsUv','Flow',#1837323,#131125);
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.read(IfcStepDeserializer.java:159)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.read(IfcStepDeserializer.java:127)
	at org.bimserver.test.TestReadWriteIFC4.test(TestReadWriteIFC4.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: java.lang.ClassCastException: The value of type 'org.eclipse.emf.ecore.impl.EClassImpl@5c77053b (name: IfcBuildingElementProxy) (instanceClassName: null) (abstract: false, interface: false)' must be of type 'org.eclipse.emf.ecore.impl.EClassImpl@51684e4a (name: IfcDistributionElement) (instanceClassName: null) (abstract: false, interface: false)'
	at org.eclipse.emf.ecore.impl.EStructuralFeatureImpl$InternalSettingDelegateSingleEObject.dynamicSet(EStructuralFeatureImpl.java:2658)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eDynamicSet(BasicEObjectImpl.java:1127)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eSet(BasicEObjectImpl.java:1101)
	at org.bimserver.emf.IdEObjectImpl.eSet(IdEObjectImpl.java:197)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eSet(BasicEObjectImpl.java:1071)
	at org.bimserver.emf.IdEObjectImpl.eSet(IdEObjectImpl.java:70)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.readReference(IfcStepDeserializer.java:603)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.processRecord(IfcStepDeserializer.java:338)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.processLine(IfcStepDeserializer.java:226)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.read(IfcStepDeserializer.java:147)
	... 31 more

Do you know about this ?

**Comment by hlg** [comment] 2020-08-26 19:24
The DeserializeException is likely a duplicate of https://github.com/opensourceBIM/BIMserver/issues/1084 (older Revit IFC exporter issue).

**Comment by hlg** [comment] 2024-11-01 18:48
Just like the Conference center file, this is from the Auckland Open IFC Model Repository: https://openifcmodel.cs.auckland.ac.nz/api/download/20160125RME_2010_Trapelo_const.ifc. It has been exported with the exact same erroneous IFC exporter. After fixing the errors (replace IfcBuildingElementProxy entities which are used in IfcRelConnectsPortToElement with IfcDistributionElement), the file can be checked in with no issue.

**Closed by hlg** 2024-11-01 18:48 UTC
